version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27021:27017"  # Expose MongoDB on port 27021 for your app
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongodb_data:/data/db
    networks:
      - dsa_network

  app:
    build: .
    container_name: dsa-sheet
    restart: always
    ports:
      - "3000:3000"  # Expose the app on port 3000
    env_file:
      - .env  # Reference the .env file here
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - dsa_network

volumes:
  mongodb_data:

networks:
  dsa_network:
    driver: bridge