version: '3.8'

services:
  app:
    build: .
    container_name: dsa-sheet
    restart: always
    links:
      - mongodb
    ports:
      - "3000:3000"  # Expose the app on port 3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27021:27017"  # Expose MongoDB on port 27021 for your app
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./data/mongo:/data/db